name: Build and Deploy to AWS ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from the Actions tab
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./docx-generator # adjust this to your app's directory

    - name: Build the application
      run: npm run build
      working-directory: ./docx-generator

    - name: Build Docker image
      run: docker build -t my-nestjs-app:latest .

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag Docker image
      run: docker tag my-nestjs-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-nestjs-app:latest

    - name: Push Docker image to ECR
      run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-nestjs-app:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: my-nestjs-app-task-def.json
        service: my-nestjs-app-service
        cluster: EHR-ECS-DEV2-ap-south-1-s
        wait-for-service-stability: true
